apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-utils-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cluster-utils-api
    spec:
      containers:
        - name: cluster-utils-api
          image: donkeyx/cluster-utils-api:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "80"
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
      imagePullSecrets:
        - name: dockerhub-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-utils-api
spec:
  selector:
    app: cluster-utils-api
  ports:
    - port: 80
      targetPort: 80
