apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-utils-api
  labels:
    app: cluster-utils
    type: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-utils
      type: api
  template:
    metadata:
      labels:
        app: cluster-utils
        type: api
    spec:
      containers:
        - name: cluster-utils-api
          image: donkeyx/cluster-utils-api:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
      initContainers:
        - name: init-dns
          image: curlimages/curl
          command:
            [
              "sh",
              "-c",
              "until curl -fsS https://google.com >> /dev/null; do sleep 2 ; done ;",
            ]
      imagePullSecrets:
        - name: dockerhub-reg-cred

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-utils-api-svc
spec:
  selector:
    app: cluster-utils
    type: api
  ports:
    - port: 8080
      targetPort: 8080
