version: 2.0

jobs:
  build-test:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run:
          name: docker-build
          command: |
            docker build -t build_container .;
            mkdir tmp;
            docker save --output tmp/build_container.tar build_container;

      - persist_to_workspace:
          root: .
          paths:
            - ./tmp

  docker-push:
    machine:
      image: ubuntu-1604:201903-01
      # docker_layer_caching: true
    environment:
      build_container: "build_container"
      dockerhub_repo: "donkeyx/cluster-utils-api"
      github_repo: "docker.pkg.github.com/donkeyx/docker_cluster-utils-api/cluster-utils-api"
      # git_hash: $(echo $CIRCLE_SHA1 | cut -c1-5)

    steps:
      - attach_workspace:
          at: .

      - run:
          name: container load
          command: |
            ls -laR;
            docker load < tmp/build_container.tar;

      - run:
          name: tag and push dockerhub
          command: |
            git_hash=$(echo $CIRCLE_SHA1 | cut -c1-8)
            echo $git_hash
            docker tag build_container $dockerhub_repo:latest
            # docker tag build_container $dockerhub_repo:${CIRCLE_TAG}-${git_hash}
            docker tag build_container $dockerhub_repo:${CIRCLE_TAG}

            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USER --password-stdin
            # docker push $dockerhub_repo:${CIRCLE_TAG}-${git_hash}
            docker push $dockerhub_repo:${CIRCLE_TAG}
            docker push $dockerhub_repo:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      # - package:
      #     requires:
      #       - build-test
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v\d+\.\d+\.\d+$/
      - docker-push:
          requires:
            - build-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
