version: 2.0

jobs:
  docker-build:
    machine:
      image: ubuntu-1604:201903-01
      # docker_layer_caching: true
    environment:
      build_container: "build_container"
      dockerhub_repo: "donkeyx/cluster-utils-api"
      github_repo: "docker.pkg.github.com/donkeyx/docker_cluster-utils-api/cluster-utils-api"
      # git_hash: $(echo $CIRCLE_SHA1 | cut -c1-5)

    steps:
      - attach_workspace:
          at: .

      - run:
          name: container build
          command: make docker-build

      - run:
          name: tag and push dockerhub
          command: |
            git_hash=$(echo $CIRCLE_SHA1 | cut -c1-8)
            echo $git_hash
            docker tag tcp-wait $dockerhub_repo:latest
            # docker tag tcp-wait $dockerhub_repo:${CIRCLE_TAG}-${git_hash}
            docker tag tcp-wait $dockerhub_repo:${CIRCLE_TAG}

            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USER --password-stdin
            # docker push $dockerhub_repo:${CIRCLE_TAG}-${git_hash}
            docker push $dockerhub_repo:${CIRCLE_TAG}
            docker push $dockerhub_repo:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      # - build-test:
      #     filters:
      #       branches:
      #         only: /.*/
      #       tags:
      #         only: /.*/
      # - package:
      #     requires:
      #       - build-test
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v\d+\.\d+\.\d+$/
      - docker-build:
          # requires:
          #   - build-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
