// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/a/control/probes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Current live/ready/startup config + startup latch + flap phase + uptime",
                "produces": [
                    "application/json"
                ],
                "summary": "Get probe control state",
                "operationId": "getProbes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProbeSnapshot"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Partial update of live/ready/startup. resetStartupLatch re-runs cold start without restarting the process.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update probe control state",
                "operationId": "putProbes",
                "parameters": [
                    {
                        "description": "probe update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ProbeUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProbeSnapshot"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/a/env": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Env dump so you can check secrets/configmaps/task params actually landed. Behind auth under /a/",
                "produces": [
                    "application/json"
                ],
                "summary": "Get environment variables",
                "operationId": "env",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer token from app logs",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/debug": {
            "get": {
                "description": "Hostname, client ip, headers, uri — good for routing tests",
                "produces": [
                    "application/json"
                ],
                "summary": "Debug",
                "operationId": "debug",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/delay/{seconds}": {
            "get": {
                "description": "Sleep N seconds (max 30) then return 200. For probe timeouts prefer LIVE/READY/STARTUP delaySeconds instead",
                "produces": [
                    "text/plain"
                ],
                "summary": "Delay then OK",
                "operationId": "delay",
                "parameters": [
                    {
                        "type": "number",
                        "description": "seconds to sleep (max 30)",
                        "name": "seconds",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "delayed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/echo": {
            "get": {
                "description": "Bounce method, path, query, headers and body back as json",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Echo request",
                "operationId": "echo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Bounce method, path, query, headers and body back as json",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Echo request",
                "operationId": "echo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Bounce method, path, query, headers and body back as json",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Echo request",
                "operationId": "echo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Bounce method, path, query, headers and body back as json",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Echo request",
                "operationId": "echo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "patch": {
                "description": "Bounce method, path, query, headers and body back as json",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Echo request",
                "operationId": "echo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/headers": {
            "get": {
                "description": "Headers as seen by the app (handy behind ingress/ALB)",
                "produces": [
                    "application/json"
                ],
                "summary": "Get headers",
                "operationId": "headers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/help": {
            "get": {
                "description": "Quick map of useful routes",
                "produces": [
                    "application/json"
                ],
                "summary": "Help",
                "operationId": "help",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/livez": {
            "get": {
                "description": "Kube liveness. 200 = fine; 503 = restart. Modes: ok|fail|delay|flap. LIVE_* env or /a/control/probes. Aliases: /healthz /health",
                "produces": [
                    "text/plain"
                ],
                "summary": "Liveness (livez)",
                "operationId": "livez",
                "parameters": [
                    {
                        "type": "string",
                        "description": "one-shot force fail with 0/false (curl only)",
                        "name": "ok",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "unhealthy",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Prometheus scrape endpoint",
                "produces": [
                    "text/plain"
                ],
                "summary": "Prometheus metrics",
                "operationId": "metrics",
                "responses": {
                    "200": {
                        "description": "metrics",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Simple alive check (not a kube probe — use /livez for that)",
                "produces": [
                    "text/plain"
                ],
                "summary": "Get ping",
                "operationId": "ping",
                "responses": {
                    "200": {
                        "description": "PONG",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Kube readiness. 200 = take traffic; 503 = leave Service endpoints. Modes: ok|fail|delay|flap. Alias: /ready",
                "produces": [
                    "text/plain"
                ],
                "summary": "Readiness (readyz)",
                "operationId": "readyz",
                "parameters": [
                    {
                        "type": "string",
                        "description": "one-shot force fail (curl only)",
                        "name": "ok",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ready",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "not ready",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/startupz": {
            "get": {
                "description": "Cold start latch: 503 until bootDelay, then sticky 200. mode=fail never latches. mode=flap oscillates until a success latches (or forever if you only hit fail phases — use flap carefully here).",
                "produces": [
                    "text/plain"
                ],
                "summary": "Startup (startupz)",
                "operationId": "startupz",
                "responses": {
                    "200": {
                        "description": "started",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "starting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/status/{code}": {
            "get": {
                "description": "Respond with whatever http status you pass (100-599). Great for ingress/retry testing",
                "produces": [
                    "text/plain"
                ],
                "summary": "Fixed status code",
                "operationId": "status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "HTTP status code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status body",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "What binary is running in this env",
                "produces": [
                    "application/json"
                ],
                "summary": "Version / build info",
                "operationId": "version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ProbeConfig": {
            "type": "object",
            "properties": {
                "bootDelaySeconds": {
                    "description": "Startup only: wall-clock seconds from process start before a success is allowed.",
                    "type": "number"
                },
                "delaySeconds": {
                    "description": "sleep before answering (0–30)",
                    "type": "number"
                },
                "flapEvery": {
                    "type": "integer"
                },
                "flapSeconds": {
                    "description": "Flap (mode=flap):\n  flapSeconds — wall-clock half-period: ok for N sec, fail for N sec, repeat (default 5).\n  flapEvery   — if \u003e 0, every Nth request fails instead of using the clock (handy for tests).",
                    "type": "number"
                },
                "mode": {
                    "description": "ok | fail | delay | flap",
                    "type": "string"
                }
            }
        },
        "handlers.ProbeSnapshot": {
            "type": "object",
            "properties": {
                "live": {
                    "$ref": "#/definitions/handlers.ProbeConfig"
                },
                "liveFlapPhase": {
                    "description": "Which half of a time-based flap we are in right now (ok|fail|n/a).",
                    "type": "string"
                },
                "ready": {
                    "$ref": "#/definitions/handlers.ProbeConfig"
                },
                "readyFlapPhase": {
                    "type": "string"
                },
                "startup": {
                    "$ref": "#/definitions/handlers.ProbeConfig"
                },
                "startupFlapPhase": {
                    "type": "string"
                },
                "startupLatched": {
                    "type": "boolean"
                },
                "startupWouldPass": {
                    "type": "boolean"
                },
                "uptimeSeconds": {
                    "type": "number"
                }
            }
        },
        "handlers.ProbeUpdate": {
            "type": "object",
            "properties": {
                "live": {
                    "$ref": "#/definitions/handlers.ProbeConfig"
                },
                "ready": {
                    "$ref": "#/definitions/handlers.ProbeConfig"
                },
                "resetStartupLatch": {
                    "type": "boolean"
                },
                "startup": {
                    "$ref": "#/definitions/handlers.ProbeConfig"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and the token from the app logs on startup (or AUTH_TOKEN env).",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Cluster Util API",
	Description:      "Drop-in HTTP util for testing probes, routing, headers, env/params and more in a cluster",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
