// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/a/control/probes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Current live/ready/startup config + startup latch + flap phase + uptime",
                "produces": [
                    "application/json"
                ],
                "summary": "Get probe control state",
                "operationId": "getProbes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProbeSnapshot"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Partial update of live/ready/startup. Example: fail readiness so the pod drops from Service endpoints (no restart). resetStartupLatch re-runs cold start without restarting the process. Auth: Authorize lock with \"Bearer dev\".",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update probe control state",
                "operationId": "putProbes",
                "parameters": [
                    {
                        "description": "Partial update — schema examples show fail-readiness shape",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ProbeUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProbeSnapshot"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/a/env": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Env dump so you can check secrets/configmaps/task params actually landed. Behind auth under /a/. Use the Authorize button (value: Bearer \u0026lt;token\u0026gt;) — do not leave a separate Authorization param empty.",
                "produces": [
                    "application/json"
                ],
                "summary": "Get environment variables",
                "operationId": "env",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/a/proxy": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Auth required (use Authorize lock: \"Bearer dev\"). North→south hits this pod; this pod calls url east-west. Response wrap includes upstream status, headers, and body. Try GET with url=https://httpbin.org/get or POST body example. Open proxy is SSRF — keep behind bearer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Proxy / hop to another service (auth)",
                "operationId": "proxy",
                "parameters": [
                    {
                        "description": "POST JSON body (preferred for full control). Example hits httpbin so you see headers/method echoed.",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProxyRequest"
                        }
                    },
                    {
                        "type": "string",
                        "default": "https://httpbin.org/get",
                        "example": "https://httpbin.org/get",
                        "description": "GET form: absolute URL to fetch",
                        "name": "url",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "GET",
                        "example": "GET",
                        "description": "GET form: HTTP method",
                        "name": "method",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "default": 15,
                        "example": 15,
                        "description": "GET form: outbound timeout",
                        "name": "timeoutSeconds",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Auth required (use Authorize lock: \"Bearer dev\"). North→south hits this pod; this pod calls url east-west. Response wrap includes upstream status, headers, and body. Try GET with url=https://httpbin.org/get or POST body example. Open proxy is SSRF — keep behind bearer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Proxy / hop to another service (auth)",
                "operationId": "proxy",
                "parameters": [
                    {
                        "description": "POST JSON body (preferred for full control). Example hits httpbin so you see headers/method echoed.",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProxyRequest"
                        }
                    },
                    {
                        "type": "string",
                        "default": "https://httpbin.org/get",
                        "example": "https://httpbin.org/get",
                        "description": "GET form: absolute URL to fetch",
                        "name": "url",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "GET",
                        "example": "GET",
                        "description": "GET form: HTTP method",
                        "name": "method",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "default": 15,
                        "example": 15,
                        "description": "GET form: outbound timeout",
                        "name": "timeoutSeconds",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/debug": {
            "get": {
                "description": "Hostname, client ip, headers, uri — good for routing tests",
                "produces": [
                    "application/json"
                ],
                "summary": "Debug",
                "operationId": "debug",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/delay/{seconds}": {
            "get": {
                "description": "Sleep N seconds then return 200. Cap is MAX_DELAY_SECONDS env (default 120, hard max 600). Try 2 for a slow upstream demo; use probe delaySeconds to trip kube timeoutSeconds.",
                "produces": [
                    "text/plain"
                ],
                "summary": "Delay then OK",
                "operationId": "delay",
                "parameters": [
                    {
                        "type": "number",
                        "default": 2,
                        "example": 2,
                        "description": "seconds to sleep",
                        "name": "seconds",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "delayed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/echo": {
            "get": {
                "description": "Bounce method, path, query, headers and body back as json. Try POST with any body and custom headers (e.g. X-Request-Id) to see what arrived.",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Echo request",
                "operationId": "echo",
                "parameters": [
                    {
                        "default": "{\"hello\":\"from-swagger\"}",
                        "example": "{\"hello\":\"from-swagger\"}",
                        "description": "optional body to echo",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Bounce method, path, query, headers and body back as json. Try POST with any body and custom headers (e.g. X-Request-Id) to see what arrived.",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Echo request",
                "operationId": "echo",
                "parameters": [
                    {
                        "default": "{\"hello\":\"from-swagger\"}",
                        "example": "{\"hello\":\"from-swagger\"}",
                        "description": "optional body to echo",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Bounce method, path, query, headers and body back as json. Try POST with any body and custom headers (e.g. X-Request-Id) to see what arrived.",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Echo request",
                "operationId": "echo",
                "parameters": [
                    {
                        "default": "{\"hello\":\"from-swagger\"}",
                        "example": "{\"hello\":\"from-swagger\"}",
                        "description": "optional body to echo",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Bounce method, path, query, headers and body back as json. Try POST with any body and custom headers (e.g. X-Request-Id) to see what arrived.",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Echo request",
                "operationId": "echo",
                "parameters": [
                    {
                        "default": "{\"hello\":\"from-swagger\"}",
                        "example": "{\"hello\":\"from-swagger\"}",
                        "description": "optional body to echo",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "patch": {
                "description": "Bounce method, path, query, headers and body back as json. Try POST with any body and custom headers (e.g. X-Request-Id) to see what arrived.",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Echo request",
                "operationId": "echo",
                "parameters": [
                    {
                        "default": "{\"hello\":\"from-swagger\"}",
                        "example": "{\"hello\":\"from-swagger\"}",
                        "description": "optional body to echo",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/headers": {
            "get": {
                "description": "Headers as seen by the app (handy behind ingress/ALB)",
                "produces": [
                    "application/json"
                ],
                "summary": "Get headers",
                "operationId": "headers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/help": {
            "get": {
                "description": "Quick map of useful routes",
                "produces": [
                    "application/json"
                ],
                "summary": "Help",
                "operationId": "help",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/livez": {
            "get": {
                "description": "Kube liveness. 200 = fine; 503 = restart. Modes: ok|fail|delay|flap. LIVE_* env or /a/control/probes. Aliases: /healthz /health",
                "produces": [
                    "text/plain"
                ],
                "summary": "Liveness (livez)",
                "operationId": "livez",
                "parameters": [
                    {
                        "type": "string",
                        "description": "one-shot force fail with 0/false (curl only)",
                        "name": "ok",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "unhealthy",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Prometheus scrape endpoint (Go + process + HTTP RED metrics)",
                "produces": [
                    "text/plain"
                ],
                "summary": "Prometheus metrics",
                "operationId": "metrics",
                "responses": {
                    "200": {
                        "description": "metrics",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Simple alive check (not a kube probe — use /livez for that)",
                "produces": [
                    "text/plain"
                ],
                "summary": "Get ping",
                "operationId": "ping",
                "responses": {
                    "200": {
                        "description": "PONG",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Kube readiness. 200 = take traffic; 503 = leave Service endpoints. Modes: ok|fail|delay|flap. Alias: /ready",
                "produces": [
                    "text/plain"
                ],
                "summary": "Readiness (readyz)",
                "operationId": "readyz",
                "parameters": [
                    {
                        "type": "string",
                        "description": "one-shot force fail (curl only)",
                        "name": "ok",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ready",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "not ready",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/startupz": {
            "get": {
                "description": "Cold start latch: 503 until bootDelay, then sticky 200. mode=fail never latches. mode=flap oscillates until a success latches (or forever if you only hit fail phases — use flap carefully here).",
                "produces": [
                    "text/plain"
                ],
                "summary": "Startup (startupz)",
                "operationId": "startupz",
                "responses": {
                    "200": {
                        "description": "started",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "starting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/status/{code}": {
            "get": {
                "description": "Respond with whatever http status you pass (100-599). Try 418 (teapot), 503, or 502 for ingress/retry tests.",
                "produces": [
                    "text/plain"
                ],
                "summary": "Fixed status code",
                "operationId": "status",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 418,
                        "example": 418,
                        "description": "HTTP status code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status body",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "What binary is running in this env",
                "produces": [
                    "application/json"
                ],
                "summary": "Version / build info",
                "operationId": "version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ProbeConfig": {
            "type": "object",
            "properties": {
                "bootDelaySeconds": {
                    "description": "Startup only: wall-clock seconds from process start before a success is allowed.\nexample: 10",
                    "type": "number",
                    "example": 10
                },
                "delaySeconds": {
                    "description": "sleep before answering (seconds)\nexample: 0",
                    "type": "number",
                    "example": 0
                },
                "flapEvery": {
                    "description": "Flap: every Nth request fails (0 = use time-based flapSeconds).\nexample: 2",
                    "type": "integer",
                    "example": 2
                },
                "flapSeconds": {
                    "description": "Flap (mode=flap): half-period seconds (default 5).\nexample: 5",
                    "type": "number",
                    "example": 5
                },
                "mode": {
                    "description": "ok | fail | delay | flap\nexample: fail",
                    "type": "string",
                    "example": "fail"
                }
            }
        },
        "handlers.ProbeSnapshot": {
            "type": "object",
            "properties": {
                "live": {
                    "$ref": "#/definitions/handlers.ProbeConfig"
                },
                "liveFlapPhase": {
                    "description": "Which half of a time-based flap we are in right now (ok|fail|n/a).",
                    "type": "string"
                },
                "ready": {
                    "$ref": "#/definitions/handlers.ProbeConfig"
                },
                "readyFlapPhase": {
                    "type": "string"
                },
                "startup": {
                    "$ref": "#/definitions/handlers.ProbeConfig"
                },
                "startupFlapPhase": {
                    "type": "string"
                },
                "startupLatched": {
                    "type": "boolean"
                },
                "startupWouldPass": {
                    "type": "boolean"
                },
                "uptimeSeconds": {
                    "type": "number"
                }
            }
        },
        "handlers.ProbeUpdate": {
            "type": "object",
            "properties": {
                "live": {
                    "$ref": "#/definitions/handlers.ProbeConfig"
                },
                "ready": {
                    "$ref": "#/definitions/handlers.ProbeConfig"
                },
                "resetStartupLatch": {
                    "description": "example: true",
                    "type": "boolean",
                    "example": true
                },
                "startup": {
                    "$ref": "#/definitions/handlers.ProbeConfig"
                }
            }
        },
        "handlers.ProxyRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "body": {
                    "description": "Optional body (string; use for JSON text, form, etc.)\nexample: {\"hello\":\"cluster\"}",
                    "type": "string",
                    "example": "{\"hello\":\"cluster\"}"
                },
                "forwardIncomingHeaders": {
                    "description": "When true (default), copy inbound request headers onto the outbound call\n(minus hop-by-hop). Tracing headers like X-Request-Id ride along.\nexample: true",
                    "type": "boolean",
                    "example": true
                },
                "forwardSensitiveHeaders": {
                    "description": "When true, also forward Authorization / Cookie from the inbound request.\nDefault false so your bearer token for *this* api is not sent east-west by accident.\nexample: false",
                    "type": "boolean",
                    "example": false
                },
                "headers": {
                    "description": "Extra headers to set/override on the outbound request\nexample: {\"X-Demo\":\"from-swagger\"}",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "X-Demo": "from-swagger"
                    }
                },
                "method": {
                    "description": "HTTP method (default GET)\nexample: GET",
                    "type": "string",
                    "example": "GET"
                },
                "raw": {
                    "description": "When true, return the upstream body as the raw HTTP response (status + headers from upstream).\nDefault false → JSON wrap with request/response/meta (includes upstream headers + body).\nexample: false",
                    "type": "boolean",
                    "example": false
                },
                "timeoutSeconds": {
                    "description": "Timeout for the outbound call (default 10; capped by MAX_DELAY_SECONDS)\nexample: 15",
                    "type": "number",
                    "example": 15
                },
                "url": {
                    "description": "Absolute URL to call (demo: httpbin echoes method/headers back as JSON)\nexample: https://httpbin.org/get",
                    "type": "string",
                    "example": "https://httpbin.org/get"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Use the top-right Authorize lock only (not a per-operation Authorization field). Value MUST be exactly: Bearer \u003ctoken\u003e  e.g. local: Bearer dev",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Cluster Util API",
	Description:      "Drop-in HTTP util for testing probes, routing, headers, env/params and more in a cluster. Swagger \"Try it out\" uses the host you opened the UI on (or override with ?host=host:port&scheme=http on /api-docs/index.html). Authorize with Bearer token from logs or AUTH_TOKEN.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
