name: Docker build and push

on:
  push:
    tags:
      - "v*"
    branches:
      - "release/*"

jobs:
  cache:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Go packages and Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            /tmp/.buildx-cache
          key: go-docker-${{ runner.os }}-${{ hashFiles('**/*.go') }}
          restore-keys: |
            go-docker-${{ runner.os }}-

  docker:
    needs: cache
    runs-on: ubuntu-latest
    environment: ci
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Cache Go packages (reuse cache from 'cache' job)
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/*.go') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (GHCR)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/donkeyx/cluster-utils-api
            docker.io/donkeyx/cluster-utils-api
          tags: |
            type=sha
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
          branches: |
            release/*

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
